### ISSUE TITLE
Add picture of schematic for easy viewing

### ISSUE THREAD

**Issue by EdjeElectronics** [sparkfun/OpAmp_Breakout-LMV358#1]
Hello,

It would be nice to have an image or .pdf of the schematic for this breakout board so we could easily view the circuit without having to download Eagle.

Thanks!
Edje

**Comment by santaimpersonator** [comment]
You can find the [pdf for the schematic](https://cdn.sparkfun.com/datasheets/BreakoutBoards/SparkFun_OpAmp_Breakout-LMV358.pdf) on the [SparkFun product page](https://www.sparkfun.com/products/9816), which is linked in the [README.md](https://github.com/sparkfun/OpAmp_Breakout-LMV358/blob/master/README.md) of this repository.
